### ISSUE TITLE
[FEATURE]: Create login and signup pages

### ISSUE THREAD

**Issue by husamql3** [ahmeddelattarr/SyntaxSphere#19]
- [ ] crash course on react
- [ ] learn about `useEffect`
- [ ] learn about `react-hook-form`
- [ ] learn about navigation in react (routes)
- [x] #20 
- [x] #21 
- [x] #22 
- [x] #23

**Comment by husamql3** [comment]
8 hours without even creating a branch.. impressive!

**Comment by ahmeddelattarr** [comment]
I was sleeping 😭
